services:
  portfolio:
    build:
      context: .
      dockerfile: ./configs/Dockerfile
    container_name: php_web_server
    ports:
      - "8080:80"
    volumes:
      - ./src:/var/www/html
      - portfolio_storage:/var/www/html/storage 
      - ./configs/000-default.conf:/etc/apache2/sites-available/000-default.conf
    networks:
      - portfolio_network
    depends_on:
      - portfolio_db

  portfolio_db:
    image: mariadb:latest
    container_name: mariadb_server
    ports:
      - "7000:3306"
    environment:
      MYSQL_ROOT_PASSWORD: "*"
      MYSQL_DATABASE: portfolio
      MYSQL_USER: portfolio_user
      MYSQL_PASSWORD: "*"
    volumes:
      - portfolio_db_data:/var/lib/mysql
      - ./configs/init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - portfolio_network

volumes:
  portfolio_db_data:
  portfolio_storage:

networks:
  portfolio_network:
    driver: bridge 
  
